Repository trazzle/trazzle-server, pull requests merged in 2024-04, with the labels that each got.

#1 Feature/issue-36
  .github/participants.yml
  .github/workflows/auto-pr-reviewer.yml
  prisma/schema.prisma
  src/modules/cities/dto/search-city.dto.ts
  src/modules/cities/entities/city.entity.ts
  src/modules/cities/service/cities.service.ts
  src/modules/conuntries/dtos/search-country.dto.ts
  src/modules/conuntries/entities/country.entity.ts
  src/modules/conuntries/service/countries.service.ts
  src/modules/core/core.module.ts
  src/modules/core/ncp/ncp.module.ts
  src/modules/core/ncp/ncp.service.ts
Labels: bug, enhancement

#4 Feature/issue-29
  src/errors/access-token-expired.error.ts
  src/errors/social-login-failed.exception.ts
  src/filters/error-response.dto.ts
  src/filters/http-exception.filter.ts
  src/main.ts
  src/modules/core/auth/auth.module.ts
  src/modules/core/auth/helpers/auth.helper.ts
  src/modules/core/auth/jwt/jwt.strategy.ts
  src/modules/core/auth/services/auth.service.ts
  src/modules/core/config/constants/env-config.constant.ts
  src/modules/core/config/custom-config.module.ts
  src/modules/users/controllers/users.controller.ts
  src/modules/users/dtos/req/update-access-token-request.dto.ts
  src/modules/users/dtos/res/social-login-response.dto.ts
  src/modules/users/dtos/res/update-access-token-response.dto.ts
Labels: enhancement, feature

#5 :sparkles: Add: 서비스이용/개인정보처리방침 약관 API 생성
  src/app.module.ts
  src/commons/constants/trazzle-service-terms.constant.ts
  src/modules/core/aws-s3/aws-s3.service.ts
  src/modules/index.ts
  src/modules/terms/terms.controller.ts
  src/modules/terms/terms.module.ts
Labels: feature

#10 Issues/traz-9
  src/filters/all-exception.filter.ts
  src/filters/error-response.dto.ts
  src/filters/http-exception.filter.ts
  src/modules/core/auth/services/auth.service.ts
Labels: enhancement, wontfix

#11 [은강] 여행국가 통계조회, 여행국가 개수 조회 API
  src/filters/all-exception.filter.ts
  src/modules/users/controllers/users.statistics.controller.ts
  src/modules/users/dtos/res/get-user-travel-statistics-response.dto.ts
  src/modules/users/services/statistics.service.ts
  src/modules/users/services/users.service.ts
  src/modules/users/users.module.ts
Labels: feature
